version: '3.8'

services:
  frontend:
    build:
      context: ./frontend/vite-project
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:8080  # Add this line

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - DB_HOST=db  # Changed from localhost to db
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=admin_pass
      - DB_NAME=db_tms
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin_pass
      - POSTGRES_DB=db_tms
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # Add this line to expose PostgreSQL port

volumes:
  postgres_data: